/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContextFragment {
  'id' : string,
  'content' : string,
  'decisionId' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'projectId' : string,
}
export interface Decision {
  'id' : string,
  'title' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'tags' : Array<string>,
  'importance' : bigint,
  'reasoning' : string,
  'projectId' : string,
  'outcome' : string,
}
export interface Project {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'tags' : Array<string>,
  'description' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createContextFragment' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'createDecision' : ActorMethod<
    [string, string, string, string, string, Array<string>, bigint],
    undefined
  >,
  'createProject' : ActorMethod<
    [string, string, string, Array<string>],
    undefined
  >,
  'deleteContextFragment' : ActorMethod<[string], undefined>,
  'deleteDecision' : ActorMethod<[string], undefined>,
  'deleteProject' : ActorMethod<[string], undefined>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContextFragment' : ActorMethod<[string], [] | [ContextFragment]>,
  'getDecisionContextFragments' : ActorMethod<[string], Array<ContextFragment>>,
  'getHighImpactDecisions' : ActorMethod<[string], Array<Decision>>,
  'getProject' : ActorMethod<[string], [] | [Project]>,
  'getProjectDecisions' : ActorMethod<[string], Array<Decision>>,
  'getProjectTags' : ActorMethod<[string], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchDecisions' : ActorMethod<[string], Array<Decision>>,
  'updateContextFragment' : ActorMethod<[string, string], undefined>,
  'updateProject' : ActorMethod<
    [string, string, string, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];