/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Project = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContextFragment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'decisionId' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'projectId' : IDL.Text,
});
export const Decision = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'tags' : IDL.Vec(IDL.Text),
  'importance' : IDL.Nat,
  'reasoning' : IDL.Text,
  'projectId' : IDL.Text,
  'outcome' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createContextFragment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createDecision' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
      ],
      [],
      [],
    ),
  'createProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'deleteContextFragment' : IDL.Func([IDL.Text], [], []),
  'deleteDecision' : IDL.Func([IDL.Text], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContextFragment' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ContextFragment)],
      ['query'],
    ),
  'getDecisionContextFragments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContextFragment)],
      ['query'],
    ),
  'getHighImpactDecisions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Decision)],
      ['query'],
    ),
  'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
  'getProjectDecisions' : IDL.Func([IDL.Text], [IDL.Vec(Decision)], ['query']),
  'getProjectTags' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchDecisions' : IDL.Func([IDL.Text], [IDL.Vec(Decision)], ['query']),
  'updateContextFragment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Project = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContextFragment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'decisionId' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'projectId' : IDL.Text,
  });
  const Decision = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'tags' : IDL.Vec(IDL.Text),
    'importance' : IDL.Nat,
    'reasoning' : IDL.Text,
    'projectId' : IDL.Text,
    'outcome' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createContextFragment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createDecision' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'createProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'deleteContextFragment' : IDL.Func([IDL.Text], [], []),
    'deleteDecision' : IDL.Func([IDL.Text], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContextFragment' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ContextFragment)],
        ['query'],
      ),
    'getDecisionContextFragments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContextFragment)],
        ['query'],
      ),
    'getHighImpactDecisions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Decision)],
        ['query'],
      ),
    'getProject' : IDL.Func([IDL.Text], [IDL.Opt(Project)], ['query']),
    'getProjectDecisions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Decision)],
        ['query'],
      ),
    'getProjectTags' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchDecisions' : IDL.Func([IDL.Text], [IDL.Vec(Decision)], ['query']),
    'updateContextFragment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };